
/*
    Generated by generate_cutlass_code.py - Do not edit.
*/

#include "wgrad_grouped_operation.h"
#include "cutlass/cutlass.h"
#include "cutlass/gemm/gemm.h"
#include "cutlass/conv/convolution.h"
#include "cutlass/conv/conv2d_problem_size.h"
#include "cutlass/conv/kernel/implicit_gemm_convolution_grouped.h"
#include "cutlass/conv/kernel/default_conv2d_wgrad.h"
#include "cutlass/conv/kernel/default_conv2d_wgrad_grouped.h"
#include "cutlass/conv/device/implicit_gemm_convolution_grouped.h"
#include "cutlass/conv/device/implicit_gemm_convolution.h"

////////////////////////////////////////////////////////////////////

using cutlass_tensorop_iwgrad_grouped_optimized_256x128x128_64x64x128_16x8x16_3_nhwc_base = typename cutlass::conv::kernel::DefaultConv2dWgradGrouped<
    int8_t, 
    cutlass::layout::TensorNHWC,
    int8_t,
    cutlass::layout::TensorNHWC,
    float, cutlass::layout::TensorNHWC,
    int32_t, 
    cutlass::arch::OpClassTensorOp, 
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<256, 128, 128>,
    cutlass::gemm::GemmShape<64, 64, 128>,
    cutlass::gemm::GemmShape<16, 8, 16>,
    cutlass::epilogue::thread::LinearCombination<
        float, 128 / cutlass::sizeof_bits<int32_t>::value,
        int32_t, float>,
    cutlass::gemm::threadblock::GemmBatchedIdentityThreadblockSwizzle, 
    3,
    cutlass::arch::OpMultiplyAdd,
    cutlass::conv::IteratorAlgorithm::kOptimized
    >::Conv2dWgradKernel;

// Derived class
struct cutlass_tensorop_iwgrad_grouped_optimized_256x128x128_64x64x128_16x8x16_3_nhwc : 
  public cutlass_tensorop_iwgrad_grouped_optimized_256x128x128_64x64x128_16x8x16_3_nhwc_base { };


///////////////////////////////////////////////////////////////////////////////////////////////////

namespace cutlass_wgrad_grouped {

// Initialize all instances
void initialize_cutlass_tensorop_iwgrad_grouped_optimized_256x128x128_64x64x128_16x8x16_3_nhwc(std::vector<Operation *> &operation_list) {


  using Operation_cutlass_tensorop_iwgrad_grouped_optimized_256x128x128_64x64x128_16x8x16_3_nhwc = cutlass::conv::device::ImplicitGemmConvolutionGrouped<
    cutlass_tensorop_iwgrad_grouped_optimized_256x128x128_64x64x128_16x8x16_3_nhwc>;

  operation_list.push_back(new Conv2dOperation<
    Operation_cutlass_tensorop_iwgrad_grouped_optimized_256x128x128_64x64x128_16x8x16_3_nhwc>(
      "cutlass_tensorop_iwgrad_grouped_optimized_256x128x128_64x64x128_16x8x16_3_nhwc"));


}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////
    